# BlockMint Main Configuration

# General Settings
settings:
  # Maximum number of generators per player (0 = unlimited)
  max-generators-per-player: 10
  
  # Whether to use holograms for generators
  use-holograms: true
  
  # Distance at which holograms become visible (blocks)
  hologram-view-distance: 16
  
  # Interval to check/update generators (in ticks, 20 ticks = 1 second)
  generator-check-interval: 100
  
  # Whether to automatically collect from generators
  auto-collect: false
  
  # Range for auto-collection (in blocks)
  auto-collect-range: 10.0
  
  # Visual effects settings
  visual-effects:
    # Whether to show particles for ready generators
    show-particles: true
    
    # Whether to play sounds for ready generators
    play-sounds: true
    
    # Whether to glow blocks when ready
    glow-when-ready: true
    
  # Item display settings
  display-item:
    # Whether to use custom model data for generator displays
    use-custom-model-data: true
    # Whether to rotate display items
    rotate-display: true
    # Rotation speed (in degrees per tick)
    rotation-speed: 2
    # Height above block
    height-offset: 1.5
    # Reanchor ticks for display items
    anchor-frequency: 20

  # Block placement settings
  block-placement:
    ensure-on-chunk-load: true

  # Particles settings
  particles:
    # Whether to show particles for ready generators
    show-ready-particles: true
    # Interval for particle display (in milliseconds)
    particle-interval: 2000

  # Sounds settings
  sounds:
    # Whether to play sounds for ready generators
    play-ready-sounds: true
    # Interval for sound playback (in milliseconds)
    sound-interval: 3000

  # Startup settings
  startup:
    initial-delay: 40
    reload-delay: 20

  # Protection settings
  protection:
    prevent-explosion: true

  # Debug settings
  debug:
    protection: false
    chunk-events: false

# Economy Settings
economy:
  # Whether to enable selling generators
  allow-selling: true
  
  # Sell value multiplier (percentage of full value)
  sell-value-multiplier: 0.75
  
  # Whether to charge for upgrades
  charge-for-upgrades: true

  # Starting value for economy
  starting-value: 10.0

# Database Settings
database:
  # How often to save data (in minutes)
  save-interval: 10
  
  # Whether to keep backups
  create-backups: true
  
  # Maximum number of backups to keep
  max-backups: 5

  # Database type and file settings
  type: sqlite
  file: blockmint.db

  # MySQL settings
  mysql:
    host: localhost
    port: 3306
    database: blockmint
    username: root
    password: password
    ssl: false

# Debug Settings
debug:
  # Whether to enable debug mode
  enabled: false
  
  # Whether to log database operations
  log-database: false
  
  # Whether to log generator operations
  log-generators: false

# Networks Settings
networks:
  visualization:
    enabled: true
    particle-density: 2
    max-distance: 50
    show-range-indicators: true
  
  tiers:
    BASIC:
      cost: 1000
      base-bonus: 0.05
      per-generator-bonus: 0.01
      max-bonus: 0.25
      range: 15
      max-generators: 5
      
    ADVANCED:
      cost: 5000
      base-bonus: 0.1
      per-generator-bonus: 0.015
      max-bonus: 0.4
      range: 20
      max-generators: 10
      
    ELITE:
      cost: 25000
      base-bonus: 0.15
      per-generator-bonus: 0.02
      max-bonus: 0.6
      range: 25
      max-generators: 15
      
    ULTIMATE:
      cost: 100000
      base-bonus: 0.2
      per-generator-bonus: 0.025
      max-bonus: 0.8
      range: 30
      max-generators: 20
      
    CELESTIAL:
      cost: 500000
      base-bonus: 0.3
      per-generator-bonus: 0.03
      max-bonus: 1.0
      range: 40
      max-generators: 30