name: BlockMint
version: '1.0.0'
main: id.rnggagib.BlockMint
api-version: '1.20'
depend: [Vault]
softdepend: [PlaceholderAPI]
authors: [RnggaGib]
description: 'A plugin that lets players place automated generators that generate money over time.'

commands:
  blockmint:
    description: Main command for BlockMint
    aliases: [bm, generators]
    usage: /<command> [subcommand] [args]
    permission: blockmint.command

permissions:
  blockmint.command:
    description: Allows using the main BlockMint command
    default: true
  blockmint.use:
    description: Allows placing and using generators
    default: true
  blockmint.admin:
    description: Gives access to all BlockMint admin commands
    default: op
    children:
      blockmint.command: true
      blockmint.reload: true
      blockmint.give: true
      blockmint.bypass.limit: true
      blockmint.admin.remove: true
  blockmint.reload:
    description: Allows reloading the plugin
    default: op
  blockmint.give:
    description: Allows giving generator items to players
    default: op
  blockmint.upgrade:
    description: Allows upgrading generators
    default: true
  blockmint.bypass.limit:
    description: Bypasses the generator limit
    default: op
  blockmint.admin.remove:
    description: Allows removing other players' generators
    default: op